on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos:
    name: macOS
    runs-on: macos-26
    strategy:
      matrix:
        xcode: ["26.0"]
        config: ["debug"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          lfs: true
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Run ${{ matrix.config }} Build
        run: swift build --configuration ${{ matrix.config }}

  android:
    name: Android
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          lfs: true
      - name: "Build Swift Package on Android"
        uses: swift-android-sdk/swift-android-action@v2
        with:
          swift-version: 6.2
          swift-configuration: debug
          run-tests: false

  linux-arm:
    name: Linux ARM
    runs-on: ubuntu-24.04-arm
    container: swift:6.2
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          lfs: true
      - name: Build Swift Package on Linux ARM
        run: swift build
